package com.studyhub.mapper;

import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import com.studyhub.entity.BrowseHistory;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.TestPropertySource;
import org.springframework.test.context.jdbc.Sql;

import static org.junit.jupiter.api.Assertions.assertEquals;

@SpringBootTest
@ActiveProfiles("test")
@TestPropertySource(properties = {
        "spring.aop.auto=false",
        "spring.datasource.url=jdbc:h2:mem:browsehistory;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE"
})
@Sql(statements = {
        "CREATE TABLE IF NOT EXISTS browse_history (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "user_id BIGINT NOT NULL, note_id BIGINT NOT NULL, " +
                "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, " +
                "CONSTRAINT uk_user_note UNIQUE (user_id, note_id))",
        "DELETE FROM browse_history"
})
class BrowseHistoryMapperIntegrationTest {

    @Autowired private BrowseHistoryMapper browseHistoryMapper;

    @Test
    void upsertKeepsOneRecordPerUserAndNote() {
        browseHistoryMapper.upsert(7L, 11L);
        browseHistoryMapper.upsert(7L, 11L);
        browseHistoryMapper.upsert(8L, 11L);

        assertEquals(1L, count(7L, 11L));
        assertEquals(1L, count(8L, 11L));
    }

    private Long count(Long userId, Long noteId) {
        return browseHistoryMapper.selectCount(new LambdaQueryWrapper<BrowseHistory>()
                .eq(BrowseHistory::getUserId, userId)
                .eq(BrowseHistory::getNoteId, noteId));
    }
}
